I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/settings.rpy", line 1, in script
    init -9 python:
  File "game/screens/settings.rpy", line 19, in <module>
    _steamlib.add_item([2])
  File "game/libs/steam/steamlib.rpy", line 637, in add_item
    response = requests.post(api_url, data=payload)
SSLError: HTTPSConnectionPool(host='crucialexperiment.su', port=443): Max retries exceeded with url: /durka_simulator/steam/add (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'crucialexperiment.su'. (_ssl.c:1129)")))

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/settings.rpy", line 1, in script
    init -9 python:
  File "D:\RenPy\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/screens/settings.rpy", line 19, in <module>
    _steamlib.add_item([2])
  File "game/libs/steam/steamlib.rpy", line 637, in add_item
    response = requests.post(api_url, data=payload)
  File "lib/python3.9/requests/api.py", line 115, in post
  File "lib/python3.9/requests/api.py", line 59, in request
  File "lib/python3.9/requests/sessions.py", line 589, in request
  File "lib/python3.9/requests/sessions.py", line 703, in send
  File "lib/python3.9/requests/adapters.py", line 517, in send
SSLError: HTTPSConnectionPool(host='crucialexperiment.su', port=443): Max retries exceeded with url: /durka_simulator/steam/add (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'crucialexperiment.su'. (_ssl.c:1129)")))

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
 
Tue Apr 23 14:33:46 2024
